name: Keycloak Docker CI

on: [push, pull_request]

jobs:
  build:
    name: Build and push docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out keycloak/keycloak-containers
        uses: actions/checkout@v2
        with:
          repository: keycloak/keycloak-containers
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: server
          file: server/Dockerfile
          pull: true
          push: true
          build-args: GIT_REPO=primesign/keycloak
          cache-from: type=registry,ref=primesign/keycloak:latest
          cache-to: type=inline
          tags: primesign/keycloak:latest