name: Docker CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  DEFAULT_JDK_VERSION: 21

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: docker-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and push docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.DEFAULT_JDK_VERSION }}
          cache: 'maven'

      - name: Build Keycloak
        run: |
          mvn clean install -DskipTestsuite -DskipExamples -DskipTests
          mvn -f quarkus/pom.xml clean install -DskipTests

      - name: Set up environment
        run: cat release-details >> $GITHUB_ENV

      - name: Copy keycloak artifact
        run: cp quarkus/dist/target/keycloak-${{env.VERSION}}.tar.gz quarkus/container/

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: primesign-services
          password: ${{ secrets.CR_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: quarkus/container
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          build-args: KEYCLOAK_DIST=keycloak-${{env.VERSION}}.tar.gz
          tags: |
            ghcr.io/primesign/keycloak:latest
            ghcr.io/primesign/keycloak:${{env.VERSION}}
            ghcr.io/primesign/keycloak:${{env.SHORT_VERSION}}

      - name: Remove keycloak artifacts before caching
        if: steps.cache.outputs.cache-hit != 'true'
        run: rm -rf ~/.m2/repository/org/keycloak