name: Keycloak Docker CI

on: [push, pull_request]
#on:
#  push:
#    branches:
#      - master

jobs:
  build:
    name: Build and push docker image
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: https://github.com/keycloak/keycloak-containers.git#master
          file: server/Dockerfile
          push: true
          build-args: GIT_REPO=primesign/keycloak
          cache-from: type=registry,ref=primesign/keycloak:latest
          cache-to: type=inline
          tags: docker.pkg.github.com/primesign/keycloak/keycloak:latest