name: Keycloak Primesign CI

on: [push, pull_request]

jobs:
  build:
    name: Build Distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build
        run: mvn -Pdistribution -pl distribution/server-dist -am -Dmaven.test.skip install
      - name: Persist Keycloak Server
        uses: actions/upload-artifact@v2
        with:
          name: keycloak-server
          path: distribution/server-dist/target/keycloak-*.tar.gz
  deploy:
    name: Push Docker image to GitHub Packages
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out keycloak/keycloak-containers
        uses: actions/checkout@v2
        with:
          repository: keycloak/keycloak-containers
      - name: Download Keycloak Server
        uses: actions/download-artifact@v1
        with:
          name: keycloak-server
          path: /tmp/keycloak-server.tar.gz
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          file: server/Dockerfile
          build-args: 'KEYCLOAK_DIST=file:///tmp/keycloak-server.tar.gz'
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: primesign/keycloak/keycloak
          tag_with_ref: true