name: Keycloak CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build
        run: mvn clean install -B -DskipTests -Pdistribution
      - name: Tar Maven Repo
        shell: bash
        run: tar -czvf maven-repo.tgz -C ~ .m2/repository
      - name: Persist Maven Repo
        uses: actions/upload-artifact@v1
        with:
          name: maven-repo
          path: maven-repo.tgz
      - name: Persist Keycloak Server
        uses: actions/upload-artifact@v1
        with:
          name: keycloak-server
          path: distribution/server-dist/target/keycloak-*.tar.gz

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Download Maven Repo
        uses: actions/download-artifact@v1
        with:
          name: maven-repo
          path: .
      - name: Extract Maven Repo
        shell: bash
        run: tar -xzvf maven-repo.tgz -C ~
      - name: Build testsuite
        run: mvn clean install -B -Pauth-server-wildfly -DskipTests -f testsuite/pom.xml
      - name: Run base tests
        run: mvn clean install -B -Pauth-server-wildfly -f testsuite/integration-arquillian/tests/base/pom.xml | misc/log/trimmer.sh; exit ${PIPESTATUS[0]}
  test-undertow-map:
    name: Test undertow - map provider
    needs: build
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: -Xmx2048m
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Download Maven Repo
        uses: actions/download-artifact@v1
        with:
          name: maven-repo
          path: .
      - name: Extract Maven Repo
        shell: bash
        run: tar -xzvf maven-repo.tgz -C ~
      - name: Build testsuite
        run: mvn clean install -B -DskipTests -f testsuite/pom.xml
      - name: Run base tests - undertow
        run: mvn clean install -B -f testsuite/integration-arquillian/tests/base/pom.xml -Dkeycloak.client.provider=map | misc/log/trimmer.sh; exit ${PIPESTATUS[0]}
  deploy:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out keycloak/keycloak-containers
        uses: actions/checkout@v2
        with:
          repository: keycloak/keycloak-containers
      - name: Download Keycloak Server
        uses: actions/download-artifact@v1
        with:
          name: keycloak-server
          path: /tmp/keycloak-server.tar.gz
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          file: server/Dockerfile
          build-args:
            - KEYCLOAK_DIST=file:///tmp/keycloak-server.tar.gz
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: primesign/keycloak/keycloak
          tag_with_ref: true